import {
  AiBrowserIcon,
  AiContentGenerator01Icon,
  Alert02Icon,
  AlertCircleIcon,
  Archive03Icon,
  ArrowDown01Icon,
  ArrowDown02Icon,
  ArrowDownDoubleIcon,
  ArrowLeft01Icon,
  ArrowMoveDownLeftIcon,
  ArrowMoveDownRightIcon,
  ArrowReloadHorizontalIcon,
  ArrowRight01Icon,
  ArrowRight02Icon,
  ArrowTurnBackwardIcon,
  ArrowTurnForwardIcon,
  ArrowUp01Icon,
  ArrowUp02Icon,
  ArrowUpDoubleIcon,
  ArrowUpDownIcon,
  ArrowUpRight01Icon,
  AttachmentIcon,
  Book02Icon,
  BotIcon,
  BrainIcon,
  BrowserIcon,
  BubbleChatAddIcon,
  BubbleChatIcon,
  Bug01Icon,
  Calendar03Icon,
  CalendarCheckOut02Icon,
  Cancel01Icon,
  CancelCircleIcon,
  ChartColumnIcon,
  CheckListIcon,
  CheckmarkCircle02Icon,
  CircleArrowShrink01Icon,
  CircleIcon,
  CleanIcon,
  Clock01Icon,
  CloudIcon,
  CloudOffIcon,
  Coffee02Icon,
  CollapseIcon,
  ComputerTerminal01Icon,
  Copy01Icon,
  DashedLine02Icon,
  DashedLineCircleIcon,
  DateTimeIcon,
  Delete02Icon,
  DiscordIcon,
  Download01Icon,
  DragDropHorizontalIcon,
  DragDropVerticalIcon,
  Edit02Icon,
  Edit04Icon,
  ElectricPlugsIcon,
  ExpandIcon,
  File01Icon,
  FileAttachmentIcon,
  FileEmpty02Icon,
  FileQuestionMarkIcon,
  Folder02Icon,
  FolderAddIcon,
  FolderEditIcon,
  FolderExportIcon,
  FolderGitTwoIcon,
  FolderIcon,
  FolderRemoveIcon,
  GitBranchIcon,
  GitForkIcon,
  GithubIcon,
  GitMergeIcon,
  GitPullRequestArrow,
  GitPullRequestClosedIcon,
  GitPullRequestDraftIcon,
  GitPullRequestIcon,
  GridViewIcon,
  HelpCircleIcon,
  InformationCircleIcon,
  InternetIcon,
  LaptopIcon,
  Layers01Icon,
  LayoutTwoColumnIcon,
  LayoutTwoRowIcon,
  LinkSquare02Icon,
  ListViewIcon,
  Loading03Icon,
  LockIcon,
  Mail02Icon,
  MailOpen01Icon,
  Menu02Icon,
  MessageAdd02Icon,
  MessageQuestionIcon,
  Mic02Icon,
  MoreHorizontalIcon,
  PackageReceiveIcon,
  PauseIcon,
  PinIcon,
  PinOffIcon,
  PlayIcon,
  PlusMinusSquare01Icon,
  PlusSignIcon,
  PuzzleIcon,
  Refresh01Icon,
  RepeatIcon,
  Search01Icon,
  SecurityCheckIcon,
  SentIcon,
  Settings01Icon,
  SidebarBottomIcon,
  SidebarLeftIcon,
  SidebarRightIcon,
  SlidersHorizontalIcon,
  SmartPhone01Icon,
  Sorting01Icon,
  SourceCodeIcon,
  SquareIcon,
  SquareUnlock02Icon,
  StarIcon,
  Target02Icon,
  TestTube01Icon,
  TextWrapIcon,
  Tick02Icon,
  TimeScheduleIcon,
  ToolboxIcon,
  ToolCaseIcon,
  Unarchive03Icon,
  UserAdd01Icon,
  UserIcon,
  ViewIcon,
  ViewOffIcon,
  WorkflowCircle03Icon,
  ZapIcon,
  ZoomInAreaIcon,
  ZoomOutAreaIcon,
} from "@hugeicons/core-free-icons";

type Glyph = readonly (readonly [string, Readonly<Record<string, string | number>>])[];

/**
 * BB's named icon vocabulary (`bb.branding.icon: "GridView"`) mapped to the
 * Hugeicons shapes BB draws for each name. Only these names are bundled, so
 * the server stays small; unknown names fall through to image discovery.
 */
const GLYPHS: Readonly<Record<string, Glyph>> = {
  AiBrowser: AiBrowserIcon,
  AiContentGenerator01: AiContentGenerator01Icon,
  AlertCircle: AlertCircleIcon,
  AlertTriangle: Alert02Icon,
  AlignLeft: Menu02Icon,
  AppWindow: BrowserIcon,
  Archive: Archive03Icon,
  ArchiveRestore: Unarchive03Icon,
  ArrowDown: ArrowDown02Icon,
  ArrowReloadHorizontal: ArrowReloadHorizontalIcon,
  ArrowRight: ArrowRight02Icon,
  ArrowTurnBackward: ArrowTurnBackwardIcon,
  ArrowTurnForward: ArrowTurnForwardIcon,
  ArrowUp: ArrowUp02Icon,
  ArrowUpDown: ArrowUpDownIcon,
  ArrowUpRight: ArrowUpRight01Icon,
  Beaker: TestTube01Icon,
  Bot: BotIcon,
  Brain: BrainIcon,
  Browser: BrowserIcon,
  Bug: Bug01Icon,
  Calendar: Calendar03Icon,
  CalendarCheckOut02: CalendarCheckOut02Icon,
  ChartColumn: ChartColumnIcon,
  Check: Tick02Icon,
  ChevronDown: ArrowDown01Icon,
  ChevronLeft: ArrowLeft01Icon,
  ChevronRight: ArrowRight01Icon,
  ChevronUp: ArrowUp01Icon,
  ChevronsDown: ArrowDownDoubleIcon,
  ChevronsUp: ArrowUpDoubleIcon,
  Circle: CircleIcon,
  CircleArrowShrink: CircleArrowShrink01Icon,
  CircleCheck: CheckmarkCircle02Icon,
  CircleQuestion: HelpCircleIcon,
  CircleX: CancelCircleIcon,
  Clean: CleanIcon,
  Clock: Clock01Icon,
  Cloud: CloudIcon,
  CloudOff: CloudOffIcon,
  Code: SourceCodeIcon,
  Coffee: Coffee02Icon,
  Columns2: LayoutTwoColumnIcon,
  ComputerTerminal01: ComputerTerminal01Icon,
  Copy: Copy01Icon,
  CornerDownLeft: ArrowMoveDownLeftIcon,
  CornerDownRight: ArrowMoveDownRightIcon,
  DateTime: DateTimeIcon,
  Discord: DiscordIcon,
  Download: Download01Icon,
  DragDropHorizontal: DragDropHorizontalIcon,
  DragDropVertical: DragDropVerticalIcon,
  Edit: Edit02Icon,
  EditFile: Edit04Icon,
  ElectricPlugs: ElectricPlugsIcon,
  Explore: Book02Icon,
  ExternalLink: LinkSquare02Icon,
  Eye: ViewIcon,
  EyeOff: ViewOffIcon,
  File: FileEmpty02Icon,
  FileAttachment: FileAttachmentIcon,
  FileDiff: PlusMinusSquare01Icon,
  FileQuestion: FileQuestionMarkIcon,
  FileText: File01Icon,
  Folder: FolderIcon,
  FolderEdit: FolderEditIcon,
  FolderExport: FolderExportIcon,
  FolderGit: FolderGitTwoIcon,
  FolderMinus: FolderRemoveIcon,
  FolderOpen: Folder02Icon,
  FolderPlus: FolderAddIcon,
  Fork: GitForkIcon,
  GitBranch: GitBranchIcon,
  GitMerge: GitMergeIcon,
  GitPullRequest: GitPullRequestIcon,
  GitPullRequestArrow: GitPullRequestArrow,
  GitPullRequestClosed: GitPullRequestClosedIcon,
  GitPullRequestDraft: GitPullRequestDraftIcon,
  Github: GithubIcon,
  Globe: InternetIcon,
  GridView: GridViewIcon,
  Info: InformationCircleIcon,
  Laptop: LaptopIcon,
  Layers: Layers01Icon,
  ListTodo: CheckListIcon,
  ListView: ListViewIcon,
  Loading: Loading03Icon,
  Lock: LockIcon,
  Mail: Mail02Icon,
  MailOpen: MailOpen01Icon,
  Maximize2: ExpandIcon,
  MessageCirclePlus: BubbleChatAddIcon,
  MessageQuestion: MessageQuestionIcon,
  MessageSquare: BubbleChatIcon,
  MessageSquarePlus: BubbleChatAddIcon,
  Mic: Mic02Icon,
  Minimize2: CollapseIcon,
  MoreHorizontal: MoreHorizontalIcon,
  NewTab: DashedLine02Icon,
  PackageReceive: PackageReceiveIcon,
  PanelBottom: SidebarBottomIcon,
  PanelLeft: SidebarLeftIcon,
  PanelRight: SidebarRightIcon,
  Paperclip: AttachmentIcon,
  Pause: PauseIcon,
  Pin: PinIcon,
  PinOff: PinOffIcon,
  Play: PlayIcon,
  Plus: PlusSignIcon,
  Puzzle: PuzzleIcon,
  Repeat: RepeatIcon,
  RotateCcw: Refresh01Icon,
  Rows2: LayoutTwoRowIcon,
  Search: Search01Icon,
  SecurityCheck: SecurityCheckIcon,
  Sent: SentIcon,
  Settings: Settings01Icon,
  SideChat: MessageAdd02Icon,
  SlidersHorizontal: SlidersHorizontalIcon,
  Smartphone: SmartPhone01Icon,
  Sort: Sorting01Icon,
  Spinner: DashedLineCircleIcon,
  Square: SquareIcon,
  SquareUnlock02: SquareUnlock02Icon,
  Star: StarIcon,
  Target: Target02Icon,
  Terminal: ComputerTerminal01Icon,
  TextWrap: TextWrapIcon,
  TimeSchedule: TimeScheduleIcon,
  ToolCase: ToolCaseIcon,
  Toolbox: ToolboxIcon,
  Trash2: Delete02Icon,
  UserRound: UserIcon,
  UserRoundPlus: UserAdd01Icon,
  Workflow: WorkflowCircle03Icon,
  X: Cancel01Icon,
  Zap: ZapIcon,
  ZoomIn: ZoomInAreaIcon,
  ZoomOut: ZoomOutAreaIcon,
};

export const GLYPH_NAMES: readonly string[] = Object.keys(GLYPHS);

/**
 * Render a BB icon name as a standalone monochrome SVG. The client draws it
 * as a CSS mask, so only the painted shape matters, never its colors.
 */
export function renderGlyphSvg(name: string): string | null {
  const glyph = GLYPHS[name.trim()];
  if (glyph === undefined) return null;

  const children = glyph
    .map(([tag, attributes]) => {
      const rendered = Object.entries(attributes)
        .filter(([key]) => key !== "key")
        .map(([key, value]) => `${toSvgAttribute(key)}="${escapeAttribute(String(value))}"`)
        .join(" ");
      return `<${tag} ${rendered}/>`;
    })
    .join("");

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none">${children}</svg>`;
}

function toSvgAttribute(key: string): string {
  return key.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
}

function escapeAttribute(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll('"', "&quot;")
    .replaceAll("<", "&lt;");
}
